[package]
name = "leech"
version = "0.1.0"
edition = "2021"
authors = ["Elijah Obara <elijahobara@samson.dev>"]
license = "AGPL-3.0"
repository = "https://github.com/obaraelijah/Ferrous-project"
description = "The worker component of Ferrous-project"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Cli parser
clap = { version = "~4", features = ["derive"] }
# regex library
regex = { version = ">=1.5.5" }

# Logging facade
log = { version = "~0.4" }
# Logging framework
env_logger = { version = "~0.10" }

# Async runtime
tokio = { version = ">=1.23.1", features = ["macros", "sync", "rt-multi-thread", "net", "time"] }
# Abstractions for async programming
futures = { version = "~0.3" }
# Tokio streams
tokio-stream = { version = "~0.1" }

# Expansion of the Iterator trait
itertools = { version = "~0.10" }

# gRPC implementation
tonic = { version = "~0.8", features = ["transport", "tls"] }
# codegenerator
prost = { version = "~0.11" }
prost-types = { version = "~0.11" }

# Serialization library
serde = { version = "~1", features = ["derive"] }
toml = { version = "~0.7" }
serde_json = { version = "~1" }
ipnet = { version = "~2" }
# Time library
chrono = { version = ">=0.4.20", features = ["serde"] }

# Lazy initialization
once_cell = { version = "~1" }

# RNG library
rand = { version = "~0.8" }

# ORM
rorm = { version = "~0.5", features = ["tokio-rustls", "cli", "uuid"] }

# Needed because of modules

# DNS resolver
trust-dns-resolver = { version = "~0.22", features = ["dns-over-https-rustls", "tokio-rustls", "tokio"] }

# icmp library
surge-ping = { version = "~0.7" }
# increase resource limit
rlimit = { version = "~0.9" }

# http request library
reqwest = { version = "~0.11", features = ["json", "trust-dns", "rustls-tls-native-roots"] }
# URL parsing lib
url = { version = "~2" }

[build-dependencies]
tonic-build = { version = "~0.8" }

[features]
rorm-main = []