[package]
name = "ferrous"
version = "0.1.0"
edition = "2021"
authors = ["Elijah Obara <elijahobara@samson.dev>"]
license = "AGPL-3.0"
repository = "https://github.com/obaraelijah/Ferrous-project"
description = "The core component of Ferrous-project"

[dependencies]
# Webframework
actix-web = { version = "~4" }
# Extensions for actix-web
actix-toolbox = { version = "~0.9", features = ["ws", "logging", "session"] }
# Webauthn library
webauthn-rs = { version = "~0.4", features = ["danger-allow-state-serialisation"] }

# openapi swagger
utoipa = { version = "~3", features = ["actix_extras", "repr", "chrono", "uuid", "openapi_extensions", "preserve_order"] }
# openapi swagger boilerplat generation
utoipa-swagger-ui = { version = "3", features = ["actix-web"] }

# Hashing
argon2 = { version = "~0.5" }

# Cli parser
clap = { version = "~4", features = ["derive"] }
# Read passwords from cli
rpassword = { version = "~7" }

# Logging facade
log = { version = "~0.4" }

# Serialization
serde = { version = "~1", features = ["derive"] }
toml = { version = "~0.7" }
serde_json = { version = "~1" }
serde_repr = { version = "~0.1" }
# Time library
chrono = { version = ">=0.4.20", features = ["serde"] }
# Bytes abstractions for network usage
bytes = { version = "~1" }
# Base64 decoder and encoder
base64 = { version = "~0.21" }
# ip networks
ipnet = { version = "~2", features = ["serde"] }

# Async runtime
tokio = { version = ">=1.23.1", features = ["rt-multi-thread", "sync", "macros"] }
# Async abstractions
futures = { version = "~0.3" }

# Utilities for RNG
rand = { version = "~0.8" }

# gRPC implementation
tonic = { version = "~0.8", features = ["transport", "tls"] }
# codegenerator
prost = { version = "~0.11" }
prost-types = { version = "~0.11" }

# ORM
rorm = { version = "~0.4", features = ["tokio-rustls"] }

[build-dependencies]
tonic-build = { version = "~0.8" }

[features]
rorm-main = []
