[tasks.cleanmodels]
command = "rm"
args = ["-f", ".models.json"]
workspace = false

[tasks.genmodels]
command = "cargo"
args = ["run", "-p", "ferrous", "-F rorm-main"]
dependencies = ["cleanmodels"]
workspace = false

[tasks.make-migrations]
command = "rorm-cli"
args = ["make-migrations"]
dependencies = ["genmodels"]
workspace = false

[tasks.migrate]
command = "rorm-cli"
args = ["migrate"]
workspace = false

[tasks.build]
command = "cargo"
args = ["build", "-p", "ferrous"]

[tasks.run]
command = "cargo"
args = ["run", "-p", "ferrous"]