[package]
name = "probe-config"
version = "0.1.0"
edition = "2021"
authors = ["Elijah Obara <elijahobara@samson.dev>"]
license = "AGPL-3.0"

[dependencies]
regex = { version = ">=1.5.5" }
log = { version = "~0.4" }