site_name: ferrous Project Documentation
site_url: "https://ferrous-project.org/"
theme:
  name: material
  logo: "assets/ferrous_logo.png"
  favicon: "assets/favicon.svg"
  icon:
    repo: "fontawesome/brands/github"
  custom_dir: overrides
  features:
    - content.tabs.link
    - content.code.annotate
  palette:
    scheme: slate
    primary: black
repo_url: https://github.com/obaraelijah/ferrous-project
repo_name: obaraelijah/ferrous-project
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  version:
    provider: mike
nav:
  - Home: index.md