name: Build & Tests on Linux

on:
  push:
    paths-ignore:
      - "*.md"
  pull_request:

jobs:
  dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Disable rustup auto-self-update and set up the environment
      - name: Setup Rust
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "1"

      - name: Install Clippy and other tools
        run: |
          rustup component add clippy
          cargo install clippy-sarif sarif-fmt

  build-linux:
    needs: dependencies
    name: Build
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Disable rustup auto-self-update and set up the environment
      - name: Setup Rust
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "1"

      - name: Build Ferrous
        run: cargo build -p ferrous

      - name: Build Leech
        run: cargo build -p leech

  clippy-analyze-linux:
    needs: dependencies
    name: Clippy Analyze
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Disable rustup auto-self-update and set up the environment
      - name: Setup Rust and Clippy
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          save-if: "false"
          shared-key: "1"

      - name: Run rust-clippy
        run: cargo clippy --workspace --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload Clippy analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
